spring:
  application:
    name: client-create-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
server:
  port: 8080
clients:
  client-get: http://localhost:8080/client/get
#http://client-get-service/client/get