spring:
  application:
    name: client-create-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/postgres
    username: postgres
    password: postgres
server:
  port: 8080