apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-create-service
  labels:
    app: client-create-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-create-service
  template:
    metadata:
      labels:
        app: client-create-service
    spec:
      containers:
        - name: client-create-service
          image: deamal/client-create-service:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: 192.168.56.1